/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRadarRouteImport } from './routes/trade-radar'
import { Route as TradeFinanceRouteImport } from './routes/trade-finance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreDealsRouteImport } from './routes/pre-deals'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as NormalizationRouteImport } from './routes/normalization'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ListingRouteImport } from './routes/listing'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as IndexRouteImport } from './routes/index'

const TradeRadarRoute = TradeRadarRouteImport.update({
  id: '/trade-radar',
  path: '/trade-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeFinanceRoute = TradeFinanceRouteImport.update({
  id: '/trade-finance',
  path: '/trade-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreDealsRoute = PreDealsRouteImport.update({
  id: '/pre-deals',
  path: '/pre-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalizationRoute = NormalizationRouteImport.update({
  id: '/normalization',
  path: '/normalization',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingRoute = ListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/engines': typeof EnginesRoute
  '/listing': typeof ListingRoute
  '/market': typeof MarketRoute
  '/normalization': typeof NormalizationRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pre-deals': typeof PreDealsRoute
  '/profile': typeof ProfileRoute
  '/trade-finance': typeof TradeFinanceRoute
  '/trade-radar': typeof TradeRadarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/engines': typeof EnginesRoute
  '/listing': typeof ListingRoute
  '/market': typeof MarketRoute
  '/normalization': typeof NormalizationRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pre-deals': typeof PreDealsRoute
  '/profile': typeof ProfileRoute
  '/trade-finance': typeof TradeFinanceRoute
  '/trade-radar': typeof TradeRadarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/engines': typeof EnginesRoute
  '/listing': typeof ListingRoute
  '/market': typeof MarketRoute
  '/normalization': typeof NormalizationRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pre-deals': typeof PreDealsRoute
  '/profile': typeof ProfileRoute
  '/trade-finance': typeof TradeFinanceRoute
  '/trade-radar': typeof TradeRadarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent'
    | '/billing'
    | '/dashboard'
    | '/engines'
    | '/listing'
    | '/market'
    | '/normalization'
    | '/opportunities'
    | '/pre-deals'
    | '/profile'
    | '/trade-finance'
    | '/trade-radar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent'
    | '/billing'
    | '/dashboard'
    | '/engines'
    | '/listing'
    | '/market'
    | '/normalization'
    | '/opportunities'
    | '/pre-deals'
    | '/profile'
    | '/trade-finance'
    | '/trade-radar'
  id:
    | '__root__'
    | '/'
    | '/ai-agent'
    | '/billing'
    | '/dashboard'
    | '/engines'
    | '/listing'
    | '/market'
    | '/normalization'
    | '/opportunities'
    | '/pre-deals'
    | '/profile'
    | '/trade-finance'
    | '/trade-radar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentRoute: typeof AiAgentRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  EnginesRoute: typeof EnginesRoute
  ListingRoute: typeof ListingRoute
  MarketRoute: typeof MarketRoute
  NormalizationRoute: typeof NormalizationRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PreDealsRoute: typeof PreDealsRoute
  ProfileRoute: typeof ProfileRoute
  TradeFinanceRoute: typeof TradeFinanceRoute
  TradeRadarRoute: typeof TradeRadarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-radar': {
      id: '/trade-radar'
      path: '/trade-radar'
      fullPath: '/trade-radar'
      preLoaderRoute: typeof TradeRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-finance': {
      id: '/trade-finance'
      path: '/trade-finance'
      fullPath: '/trade-finance'
      preLoaderRoute: typeof TradeFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-deals': {
      id: '/pre-deals'
      path: '/pre-deals'
      fullPath: '/pre-deals'
      preLoaderRoute: typeof PreDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normalization': {
      id: '/normalization'
      path: '/normalization'
      fullPath: '/normalization'
      preLoaderRoute: typeof NormalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing': {
      id: '/listing'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof ListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentRoute: AiAgentRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  EnginesRoute: EnginesRoute,
  ListingRoute: ListingRoute,
  MarketRoute: MarketRoute,
  NormalizationRoute: NormalizationRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PreDealsRoute: PreDealsRoute,
  ProfileRoute: ProfileRoute,
  TradeFinanceRoute: TradeFinanceRoute,
  TradeRadarRoute: TradeRadarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
